coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "examples/**"
  - "**/*_test.go"
  - "**/test_*.go"
