coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "examples/**"
  - "**/*_test.go"
  - "**/test_*.go"
