run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - stylecheck
    - unconvert
    - unparam
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gofmt:
    simplify: true

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen

    # Disable appendCombine for simplicity
    - linters:
        - gocritic
      text: "appendCombine"

    # Disable errcheck for ast_comparator (type assertions are safe)
    - path: pkg/grammar/ast_comparator\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
